import Head from "next/head";
import React from "react";
import StudentSection from "../../../components/admin/contact/student-section";
import TeacherSection from "../../../components/admin/contact/teacher-section";
import { AdminLayout } from "../../../layouts";

type Props = {};

const index = (props: Props) => {
  return (
    <>
      <Head>
        <title>Admin | Contact</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AdminLayout>
        <div className="px-8 py-4">
          <div className="mb-3 mt-16 lg:mt-0">
            <TeacherSection />
          </div>
          <div>
            <StudentSection />
          </div>
        </div>
      </AdminLayout>
    </>
  );
};

export default index;
