import Head from "next/head";
import React, { useEffect } from "react";

// @@ internal component imports @@ //;
import EditProfile from "@components/student/dashboard/edit-profile/edit-profile";
import { DashboardLayout } from "@layouts";
import { useGetUserInfoQuery } from "@redux/slices/apiSlice";

// @@====================== Profile ===========================@@ //
const Profile = () => {
  return (
    <div>
      <Head>
        <title>Edit Profile</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <DashboardLayout>
        <EditProfile />
      </DashboardLayout>
    </div>
  );
};

export default Profile;
