import Head from "next/head";
import React from "react";
import AllMessages from "../../../../components/student/dashboard/inbox/all-messages";
import Conversation from "../../../../components/student/dashboard/inbox/conversation";
import { DashboardLayout } from "../../../../layouts";

type Props = {};

const Inbox = (props: Props) => {
  return (
    <div>
      <Head>
        <title>Inbox</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <DashboardLayout>
        <section className="grid grid-cols-12 gap-6 mt-3">
          <div className="col-span-5">
            <AllMessages/>
          </div>
          <div className="col-span-7">
            <Conversation/>
          </div>
        </section>
      </DashboardLayout>
    </div>
  );
};

export default Inbox;
