import Head from "next/head";
import React from "react";
import DashboardLayout from "..";

type Props = {};

const Profile = (props: Props) => {
  return (
    <div>
      <Head>
        <title>Profile</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <DashboardLayout>
        <h1>Hello</h1>
        <h1>Hello</h1>
        <h1>Hello</h1>
        <h1>Hello</h1>
        <h1>Hello</h1>
        <h1>Hello</h1>
      </DashboardLayout>
    </div>
  );
};

export default Profile;
