// Generated by https://quicktype.io

export interface Result {
  status: string;
  result: UserInfo | WaletInfo;
}

export interface UserInfo {
  _id: string;
  name: string;
  email: string;
  phoneNumber: string;
  role: string;
  currentInstitution: CurrentInstitution;
  status: string;
  preferredMedium: any[];
  availability: any[];
  tuitionSubjects: any[];
  createdAt: string;
  updatedAt: string;
  __v: number;
}

export interface CurrentInstitution {
  name: string;
  department: string;
}

export interface WaletInfo {
  balance:number;
  email:string;
  role:string;
  __v:number;
  _id:string;
  transaction:Transaction[]
}

export interface Transaction {
  amount: number;
  operator: string;
  status: string;
  trxId: string;
  _id: string;
}
