import Head from "next/head";
import React from "react";
import AdminBalanceCard from "../../../components/admin/wallet/balance-card";
import PaymentHistory from "../../../components/admin/wallet/payment-history";
import PurchaseReqStudent from "../../../components/admin/wallet/purchase-req-student";
import { AdminLayout } from "../../../layouts";

type Props = {};

const Wallet = (props: Props) => {
  return (
    <div>
      <Head>
        <title>Admin | wallet</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AdminLayout>
        <div className="px-4 lg:grid grid-cols-12 gap-3">
          <div className="col-span-8 lg:my-3 py-16 lg:py-0">
            <PurchaseReqStudent />
            <div>
              <PaymentHistory />
            </div>
          </div>
          <div className="col-span-4 bg-[#EBEBEB] rounded-2xl lg:rounded-l-2xl h-screen mx-0 lg:px-2 py-2 lg:py-0">
            <AdminBalanceCard/>
          </div>
        </div>
      </AdminLayout>
    </div>
  );
};

export default Wallet;
