import Head from "next/head";
import { useSession } from "next-auth/react";
import { useRouter } from "next/router";
import { useEffect } from "react";
import { DashboardCard } from "../../components";
import { AdminLayout, DashboardLayout } from "../../layouts";

type Props = {
  children: React.ReactNode;
};

const Admin = ({ children }: Props) => {
  const { data: session, status } = useSession();
  const router = useRouter();
  useEffect(() => {
    if (status === "unauthenticated") router.replace("/");
  }, [router, status]);

  if (status === "loading" || status === "unauthenticated")
    return (
      <div className="flex justify-center items-center section-container bg-slate-200">
        <div className="border border-blue-300 shadow rounded-md p-4 max-w-sm w-full mx-auto"></div>
      </div>
    );

  return (
    <>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AdminLayout>
        <div className="px-6 mt-6">
          <h1>admin</h1>
        </div>
      </AdminLayout>
    </>
  );
};

export default Admin;
