import Head from "next/head";
import { useSession } from "next-auth/react";
import { useRouter } from "next/router";
import { useEffect } from "react";
import { DashboardCard } from "../../components";
import { AdminLayout, DashboardLayout } from "../../layouts";

type Props = {
  children: React.ReactNode;
};

const Admin = ({ children }: Props) => {
  const { data: session, status } = useSession();
  const router = useRouter();
  useEffect(() => {
    if (status === "unauthenticated") router.replace("/");
  }, [router, status]);

  if (status === "loading" || status === "unauthenticated")
    return (
      <div className="flex justify-center items-center section-container bg-slate-200">
        <div className="border border-blue-300 shadow rounded-md p-4 max-w-sm w-full mx-auto"></div>
      </div>
    );

  return (
    <>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AdminLayout>
        <div className="px-6">
          <div className="grid grid-cols-12 gap-4">
            <div className="col-span-6 p-4 pb-0">
              <div className="grayDiv p-4 rounded-3xl mt-4">
                <div className="titleTab bg-white font-semibold text-textSecondary">
                  Upcomming Sessions
                </div>
                <div className="p-4"></div>
              </div>
            </div>
            <div className="col-span-6 p-4 pb-0">
              <h1 className="font-light text[#7D7D7D] mb-1.5">Background</h1>
              <p className="text-[#7D7D7D] font-semibold">Science</p>
            </div>
            <div className="col-span-6"></div>
          </div>
        </div>
      </AdminLayout>
    </>
  );
};

export default Admin;
