import Head from "next/head";
import React from "react";

// @@ imports css @@ //
import EditProfile from "@components/teacher/dashboard/edit-profile/edit-profile";
import { DashboardLayout } from "@layouts";

// @@============================ Profile ============================@@ //
const Profile = () => {
  return (
    <div>
      <Head>
        <title>Edit Profile</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <DashboardLayout>
        <EditProfile />
      </DashboardLayout>
    </div>
  );
};

export default Profile;
