import Head from "next/head";
import React from "react";
import CompletedSessions from "../../../components/admin/student/completed-sessions";
import StateInfo from "../../../components/admin/student/state-info";
import StudentInfo from "../../../components/admin/student/student-info";
import AccessControl from "../../../components/admin/teacher/acces-control";
import { AdminLayout } from "../../../layouts";

type Props = {};

const index = (props: Props) => {
  return (
    <>
      <Head>
        <title>Admin | Student</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AdminLayout>
        <div className="lg:grid grid-cols-12 gap-6 py-20 lg:py-0">
          <div className="col-span-8 p-3 lg:p-7">
            <StudentInfo />
            <div>
              <StateInfo />
            </div>
            <CompletedSessions />
          </div>
          <div className="col-span-4 bg-[#EBEBEB] rounded-2xl lg:rounded-l-2xl h-screen mx-2 lg:mx-0 px-2 pt-6 lg:pt-0 pb-64 lg:pb-0">
            <AccessControl />
          </div>
        </div>
      </AdminLayout>
    </>
  );
};

export default index;
