import Head from "next/head";
import React, { useEffect, useState } from "react";
import {
  LocalImage,
  TransactionHistoryTable,
  TeacherBalanceCard,
} from "../../../../components";
import { DashboardLayout } from "../../../../layouts";
import { useGetUserInfoQuery } from "../../../../redux/slices/apiSlice";
import { UserInfo } from "../../../../types/user";
import WalletCard1 from "../../../../assets/img/wallet-card1.png";

type Props = {};

const TeacherWallet = (props: Props) => {
  const [userInfo, setUserInfo] = useState<UserInfo | undefined>(undefined);
  const { data, error, isLoading, isFetching, isSuccess }: any =
    useGetUserInfoQuery();

  useEffect(() => {
    if (data) setUserInfo(data.result);
  }, [data]);

  console.log(userInfo);

  return (
    <div>
      <Head>
        <title>Wallet</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <DashboardLayout>
        <section className="lg:grid grid-cols-12 gap-6 mt-3">
          <div className="col-span-8">
            <div className="relative">
              <LocalImage src={WalletCard1} width={260} />
              <h1 className="absolute top-1/2 left-9 -translate-y-1/2 text-white flex flex-col leading-none font-bold text-3xl">
                1250<span>US</span>
              </h1>
            </div>
            <TransactionHistoryTable />
          </div>
          <div className="col-span-4">
            <TeacherBalanceCard />
          </div>
        </section>
      </DashboardLayout>
    </div>
  );
};

export default TeacherWallet;
