import axios from "axios";
import { signIn } from "next-auth/react";
import Head from "next/head";
import { useRouter } from "next/router";
import { useState } from "react";
import { toast } from "react-hot-toast";

// @@ internal imports @@ //
import wave from "@assets/img/wave2.png";
import { BtnPrimary, InputBox, LocalImage } from "@components";

// @@ login @@ //
const Login = () => {
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const router = useRouter();

  const handleLogin = async () => {
    if (!email || !password) {
      toast.error("Please fill up all fields");
      return;
    }
    toast.loading("Waiting for Response");

    const data = {
      email: email,
      password: password,
    };

    const res: any = await signIn("credentials", { ...data, redirect: false });
    console.log(res?.status);
    toast.dismiss();

    if (res?.status !== 200) {
      toast.error("Invalid email or password");
      return;
    } else {
      toast.success("Login Successful");
      router.push("/student/dashboard");
    }
  };

  return (
    <>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="relative flex items-center justify-center h-screen overflow-hidden">
        <div className="absolute top-0 flex flex-wrap items-center justify-center phase2-wave">
          <LocalImage
            src={wave}
            alt="Hero Section Image"
            layout="fill"
            position="top"
          />
          {/* 
          //* This is the Login form modal
          */}
          <div className="z-20 -mt-8 form-modal">
            <h1 className="mx-2 text-2xl font-semibold text-right text-primaryDark">
              x
            </h1>
            <h1 className="mx-4 my-8 text-xl text-primaryDark">Welcome!</h1>
            <div className="flex flex-col items-center mx-9 mt-14">
              <InputBox
                className="pb-5"
                onChange={(e) => setEmail(e.target.value)}
                type="email"
                placeholder="Email"
              />
              <InputBox
                className="pb-5 mt-5"
                onChange={(e) => setPassword(e.target.value)}
                type="password"
                placeholder="Password"
              />
              <BtnPrimary
                onClick={handleLogin}
                className="mt-4"
                label="Login"
              />
              <p
                className="cursor-pointer text-textSecondary my-7"
                onClick={() => router.push("/register")}
              >
                Create Account
              </p>
              <p className="cursor-pointer text-textSecondary">
                Forget Password ?
              </p>
            </div>
          </div>
        </div>
      </div>
    </>
  );
};

export default Login;
