import Head from "next/head";
import logo from "@assets/img/logo.png";
import wave from "@assets/img/opening-wave1.png";
import { BtnSecondary, LocalImage, Navbar } from "@components";

type Props = {};

const OpeningInterface = (props: Props) => {
  return (
    <>
      <Head>
        <title>Welcome</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className="relative flex justify-center h-screen">
        <div className="relative z-10 openingLogo">
          <LocalImage src={logo} alt="Hero Section Image" layout="fill" />
        </div>
        <div className="absolute bottom-0 flex items-center justify-center openingWave">
          <LocalImage
            src={wave}
            alt="Hero Section Image"
            layout="fill"
            position="bottom"
          />
          <div className="z-20 pt-20">
            <BtnSecondary
              className="z-20 mr-60"
              label="Student"
              link="/student/category"
            />
            <BtnSecondary className="z-20" label="Teacher" link="/teacher" />
          </div>
        </div>
      </div>
    </>
  );
};

export default OpeningInterface;
