import Head from "next/head";
import { BannerSection } from "../components";
import { HomepageLayout } from "../layouts";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Heilo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HomepageLayout>
        <BannerSection />
      </HomepageLayout>
    </div>
  );
}
