import axios from "axios";
import { signIn } from "next-auth/react";
import Head from "next/head";
import { useRouter } from "next/router";
import { useState } from "react";
import wave from "../assets/img/wave2.png";
import { BtnPrimary, InputBox, LocalImage } from "../components";
import { toast } from "react-hot-toast";

type Props = {};

const Login = (props: Props) => {
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const router = useRouter();

  const handleLogin = async () => {
    if (!email || !password) {
      toast.error("Please fill up all fields");
      return;
    }
    toast.loading("Waiting for Response");

    const data = {
      email: email,
      password: password,
    };

    const res: any = await signIn("credentials", { ...data, redirect: false });
    console.log(res?.status);
    toast.dismiss();

    if (res?.status !== 200) {
      toast.error("Invalid email or password");
      return;
    } else {
      toast.success("Login Successful");
      router.push("/student/dashboard");
    }
  };

  return (
    <>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex justify-center items-center h-screen relative overflow-hidden">
        <div className="phase2-wave absolute top-0 flex flex-wrap justify-center items-center">
          <LocalImage
            src={wave}
            alt="Hero Section Image"
            layout="fill"
            position="top"
          />
          {/* 
          //* This is the Login form modal
          */}
          <div className="form-modal z-20 -mt-8">
            <h1 className="text-primaryDark font-semibold text-2xl text-right mx-2">
              x
            </h1>
            <h1 className="text-primaryDark text-xl mx-4 my-8">Welcome!</h1>
            <div className="mx-9 mt-14 flex flex-col items-center">
              <InputBox
                className="pb-5"
                onChange={(e) => setEmail(e.target.value)}
                type="email"
                placeholder="Email"
              />
              <InputBox
                className="pb-5 mt-5"
                onChange={(e) => setPassword(e.target.value)}
                type="password"
                placeholder="Password"
              />
              <BtnPrimary
                onClick={handleLogin}
                className="mt-4"
                label="Login"
              />
              <p
                className="text-textSecondary cursor-pointer my-7"
                onClick={() => router.push("/register")}
              >
                Create Account
              </p>
              <p className="text-textSecondary cursor-pointer">
                Forget Password ?
              </p>
            </div>
          </div>
        </div>
      </div>
    </>
  );
};

export default Login;
