import Head from "next/head";
import React from "react";
import AccessControl from "../../../components/admin/teacher/acces-control";
import Due from "../../../components/admin/teacher/due";
import Paid from "../../../components/admin/teacher/paid";
import PaymentRequest from "../../../components/admin/teacher/payment-request";
import { AdminLayout } from "../../../layouts";

type Props = {};

const TeacherAdmin = (props: Props) => {
  return (
    <>
      <Head>
        <title>Admin | Teacher</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AdminLayout>
        <div className="lg:grid grid-cols-12 gap-3 mb-64 md:mb-[450px] lg:mb-0">
          <div className="col-span-8 py-7">
            <PaymentRequest />
            <div className="lg:flex justify-center px-4 mt-20 lg:space-x-3">
              <Paid />
              <Due />
            </div>
          </div>
          <div className="col-span-4 bg-[#EBEBEB] rounded-2xl lg:rounded-l-2xl h-screen mx-4 lg:mx-0 lg:px-2 py-2 lg:py-0">
            <AccessControl />
          </div>
        </div>
      </AdminLayout>
    </>
  );
};

export default TeacherAdmin;
